name: SCore
author: Ssomar
version: ${project.version}
main: com.ssomar.score.SCore
api-version: 1.13
softdepend: [ExecutableItems, SParkour, ExecutableBlocks, CustomPiglinsTrades, Vault, Multiverse-Core]
loadbefore: [ExecutableItems, SParkour, ExecutableBlocks, CustomPiglinsTrades]