name: SCore
author: Ssomar
version: ${project.version}
main: com.ssomar.score.SCore
api-version: 1.13
softdepend: [ PolymartHelper, Polymart, ExecutableItems, SParkour, ExecutableBlocks, ExecutableEvents, CustomPiglinsTrades, MMOCore, Vault, Multiverse-Core, Lands, WorldGuard, IridiumSkyblock, BentoBox, PlaceholderAPI, GriefPrevention, GriefDefender, CoreProtect, PlotSquared, CMI, AureliumSkills, MythicMobs, ShopGUIPlus, RoseLoot, ItemsAdder, DecentHolograms, HolographicDisplaysAPI, HolographicDisplays, Better-Enchantments]
loadbefore: [ ExecutableItems, SParkour, ExecutableBlocks, ExecutableEvents, CustomPiglinsTrades ]
commands:
  score:
    description: score command
    usage: /<command> [ reload | inspect-loop ]
permissions:
  score.*:
    description: SCore permission
    default: op
    children:
      ei.cmds: true
  score.cmds:
    description: Allows SCore commands
    default: op
    children:
      score.cmd.reload: true
      score.cmd.inspect-loop: true
  score.cmd.reload:
    description: Allows the command /score reload
  score.cmd.inspect-loop:
    description: Allows the command /score inspect-loop
